name: dokan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash:  ^2.4.0
  logger: ^2.3.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/d.png"
  background_color: "#FF9B86"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:  
  color: "#FE917A"
  # image: assets/icons/dokan.png
  android: true
  ios: true
  
  android_12:
    color: "#FE917A"

flutter:
  uses-material-design: true
  assets:
    - assets/response.json
    - assets/png/
    - assets/svg/
flutter_gen:
  output: lib/src/gen/
   